#!/usr/bin/env sh

# This repo is organized by topic
source ${DOTFILES_DIR}/git
source ${DOTFILES_DIR}/instawork
source ${DOTFILES_DIR}/random
source ${DOTFILES_DIR}/sleep

# Things that don't belong in any of the above topics live here
export ANDROID_HOME='/Users/dikarel/Library/Android/sdk'
export COCOAPODS_DISABLE_STATS=1
export PATH="$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools"
export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/dikarel/Library/Android/sdk/tools:/Users/dikarel/Library/Android/sdk/platform-tools:/Users/dikarel/.vimpkg/bin:/Users/dikarel/flutter/bin:$PATH
export PS1="\w: "
