#!/usr/bin/env sh

# hub command line
eval "$(hub alias -s)"
alias pr='hub pull-request'

# Git shortcuts
alias add='git add'
alias checkout='git checkout'
alias commit='git commit'
alias diff='git difftool'
alias merge='git merge'
alias pull='git pull'
alias push='git push'
alias status='git status'

# Mnemonics
alias cm='commit'
alias co='checkout'
alias cob='checkout -b'
alias com='checkout master && pull'
alias gmom='git pull && git merge origin/master'
alias hh='push'
alias mm='merge'
alias pp='pull'
alias st='status'
