#!/usr/bin/env sh

# Yarn commands
alias fresh='yarn start:fresh'
alias generate='yarn generate'
alias install='yarn install'
alias lint='yarn test:lint'
alias release='yarn run:android:release'
alias run='yarn run:ios'
alias start='yarn start'
alias storybook='yarn storybook'
alias test='yarn test'

# System commands
alias stop='echo Killing all dev processes && killall flow esprint node watchman'
alias clean='yarn cache clean && npm cache clean --force'

# Mnemonics
alias bb='story'
alias cl='clear'
alias ff='fresh'
alias gg='generate'
alias ggbb='gg && bb'
alias ggff='gg && ff'
alias ggss='gg && ss'
alias ggtt='gg && tt'
alias hhxx='hh && xx'
alias ii='install --force'
alias iigg='ii && gg'
alias iiggbb='ii && gg && bb'
alias iiggff='ii && gg && ff'
alias iiggtt='ii && gg && tt'
alias rr='run'
alias rrxx='rr && xx'
alias ss='start'
alias tt='test'
alias xx='exit'
